### ISSUE TITLE
Fahrenheit to Celsius conversion seems off

### ISSUE THREAD

**Issue by CatherineH** [python-quantities/python-quantities#102]
I'm seeing the following behaviour:

```
>>> import quantities as q
>>> blo = 70*q.degF
>>> blo
array(70.0) * degF
>>> blo.rescale(q.degC)
array(38.88888888888889) * degC
>>> blo2 = 20*q.degC
>>> blo2.rescale(q.degF)
array(36.0) * degF
```

So... 70* F = 38.8888 *C, and 20*C = 36* F?

Google says 70 F is 21 C

Am I using this library incorrectly?

I am using the latest version of quantities from PyPI, which is 0-unknown

**Comment by CatherineH** [comment]
It looks like, as currently defined, F = K/1.8, C=K, which is where these numbers are coming from:

https://github.com/python-quantities/python-quantities/blob/bc3feb44a9df834196bd368f9853c7caf6f61b49/quantities/units/temperature.py#L16

**Comment by CatherineH** [comment]
Oh, I see, the rescale cannot handle offsets.

**Comment by ddale** [comment]
Yes, the offset is the issue. This is documented in the tutorial at http://python-quantities.readthedocs.org/en/latest/user/tutorial.html :

Attention

Quantities is not a package for describing coordinate systems that require a point of reference, like positions on a map. In particular, Quantities does not support absolute temperature scales. Instead, temperatures are assumed to be temperature differences. For example:

>>> T = 20 * pq.degC
>>> print T.rescale('K')
20.0 K
Proper support of coordinate systems would be a fairly large undertaking and is outside the scope of this project.
