### ISSUE TITLE
LookupError: Unable to parse units: "mbar"

### ISSUE THREAD

**Issue by ecarreau** [python-quantities/python-quantities#104]
When trying to create a quantity with mbar unit like this:

import quantities
val = quantities.Quantity(1.0,'mbar')

I get the error : LookupError: Unable to parse units: "mbar"

while mbar is defined in the units/pressure.py file.

Thanks for your help

**Comment by ddale** [comment]
If you are using the Quantity constructor, you have to use 

val = quantities.Quantity(1.0,'millibar')

or 

val = quantities.Quantity(1.0,'mb')
