### ISSUE TITLE
linspace() fails with numpy 1.11

### ISSUE THREAD

**Issue by rproepp** [python-quantities/python-quantities#105]
In numpy 1.11, linspace calls astype with the `copy` parameter set to `False`. When using Quantities as parameters to linspace, this fails because the astype function from Quantity only accepts the `dtype` parameter.

**Comment by w-klijn** [comment]
I have encountered the same issue:
 Minimal code example:
#######################
import numpy as np

import quantities as pq

print ("Using floats:")
np.linspace(0.0, 1.0 , 20 + 1, endpoint=True)
print ("success \n")

start_pq = 0 * pq.s
end_pq = 1 * pq.s

try:

    print ("Using quantities:")
    np.linspace(start_pq, end_pq, 20 + 1, endpoint=True)
    print ("success \n")

except Exception, e:

    print ("fail with error: \n" + str(e))

#######################
astype() got an unexpected keyword argument 'copy'
Traceback (most recent call last):

    File "minimal_example.py", line 15, in <module>

        np.linspace(start_pq, end_pq, 20 + 1, endpoint=True)

    File "/global/opt/jsc/Python-2.7.12/lib/python2.7/site-packages/numpy/core/function_base.py", line 125, in linspace

        return y.astype(dtype, copy=False)
