### ISSUE TITLE
Decibels?

### ISSUE THREAD

**Issue by techn0mad** [python-quantities/python-quantities#118]
Hi all: I'd like to use python-quantities for units of [Decibels](https://en.wikipedia.org/wiki/Decibel), and I was surprised to find that they do not currently exist in the package. Is this a design decision? Is there some policy that only physical units are supported, and not relative units such as the Decibel?
Assuming that there is no such policy, would it be correct to assume that Decibels themselves would belong in the dimensionless units category, and things like dBm and dBuV would belong in the power and electromagnetic categories, respectively? Or would they all be under the dimensionless category?

**Comment by ddale** [comment]
Are you familiar with the disclaimer about measurement scales not being supported? It's mentioned at the end of the tutorial in the documentation.

**Comment by techn0mad** [comment]
I did see that, and I understood that for a unit like degrees of temperature, there is a policy that the package would support the value and units of a temperature measurement, but not a reference value. I assume that you are saying that because Decibels require referencing the difference between two values, they are not supported?

**Comment by techn0mad** [comment]
Just to clarify my last question: temperatures have a value, units, and an implied absolute reference (e.g. -273.15 degrees C == 0 degrees K). Measurements in Decibels have a value, units, and are implicitly relative to another value in Decibels which is not absolute. I'm assuming from your answer that the policy is that values that require another value for interpretation, whether it is absolute or relative, are not supported. Is that correct?

**Comment by ddale** [comment]
I guess I am not familiar enough with the units you are talking about, and how they are used and what operations on them need to be supported, to feel comfortable including them in the package at this time.
