### ISSUE TITLE
Division of heat flow and mass flow results in magnitude of zero 

### ISSUE THREAD

**Issue by thopy** [python-quantities/python-quantities#124]
This code causes wrong output:

```

import quantities as qnt

data = {}
data['Q_gui'] = qnt.Quantity(2859, 'kW')
data['mDot_Sek']  = qnt.Quantity(123100, 'kg/h')
test = data['Q_gui'] / data['mDot_Sek'] 
print test
```

Result is 
`0 h*kW/kg`

Doing 
```
test_Q = qnt.Quantity(2859, 'kW').simplified
test_mDot = qnt.Quantity(123100, 'kg/h').simplified
test3 = test_Q  / test_mDot
print test3

```

results in 
`83610.0731113 m**2/s**2`

The unit conversion works but the magnitude should in any case be more than zero.

I do not have the programming skills to find the cause of the problem by myself. I will try to understand the code step by step but any contribution  will be highly appreciated. 

I am doing a calculation project where I am solving physical equations all over the place and I am using the quantities package extensively. Yes, I have the read the comment that the package is not yet ready for serious use but until today everything worked just fine.

**Comment by ddale** [comment]
That works as expected, you defined your quantity with an integer-typed magnitude.

**Comment by thopy** [comment]
Sorry you are completely right, I forgot that python cannot calculate 1 / 2  ;-) I have to write 1.0 / 2.0 I remember now. Anyway, I am very relieved, that you responded within 2 hours. That means the project lives. Thanks a lot and sorry for my newbee question.
