### ISSUE TITLE
ufunc <ufunc 'positive'> not supported by quantities

### ISSUE THREAD

**Issue by bakrag** [python-quantities/python-quantities#128]
Hi,
I 've got following error while trying to import neo lib:

`In [1]: import neo
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-c6026af1d1a2> in <module>()
----> 1 import neo

c:\python27\lib\site-packages\neo\__init__.py in <module>()
      9 logging_handler = logging.StreamHandler()
     10
---> 11 from neo.core import *
     12 from neo.io import *
     13 from neo.version import version as __version__

c:\python27\lib\site-packages\neo\core\__init__.py in <module>()
     31 from neo.core.block import Block
     32 from neo.core.segment import Segment
---> 33 from neo.core.channelindex import ChannelIndex
     34 from neo.core.unit import Unit
     35

c:\python27\lib\site-packages\neo\core\channelindex.py in <module>()
     12
     13 import numpy as np
---> 14 import quantities as pq
     15
     16 from neo.core.container import Container

c:\python27\lib\site-packages\quantities\__init__.py in <module>()
    283 from .unitquantity import *
    284
--> 285 from .units import *
    286
    287 from . import constants

c:\python27\lib\site-packages\quantities\units\__init__.py in <module>()
      7 from .prefixes import *
      8
----> 9 from . import acceleration
     10 from .acceleration import *
     11

c:\python27\lib\site-packages\quantities\units\acceleration.py in <module>()
      5
      6 from ..unitquantity import UnitQuantity
----> 7 from .time import s
      8 from .length import m
      9

c:\python27\lib\site-packages\quantities\units\time.py in <module>()
     16     s/1000,
     17     'ms',
---> 18     aliases=['milliseconds']
     19 )
     20 us = microsecond = UnitTime(

c:\python27\lib\site-packages\quantities\unitquantity.pyc in __new__(cls, name, definition, symbol, u_symbol, aliases, doc)
     60                 definition *= dimensionless
     61             ret._definition = definition
---> 62             ret._conv_ref = definition._reference
     63         else:
     64             ret._definition = None

c:\python27\lib\site-packages\quantities\quantity.pyc in _reference(self)
    137         rq = 1*unit_registry['dimensionless']
    138         for u, d in self.dimensionality.items():
--> 139             rq = rq * u._reference**d
    140         return rq * self.magnitude
    141

c:\python27\lib\site-packages\quantities\unitquantity.pyc in __pow__(self, other)
    228     @with_doc(Quantity.__pow__, use_header=False)
    229     def __pow__(self, other):
--> 230         return self.view(Quantity).__pow__(other)
    231
    232     @with_doc(Quantity.__rpow__, use_header=False)

c:\python27\lib\site-packages\quantities\quantity.pyc in g(self, other, *args)
     86         except AssertionError:
     87             raise ValueError('Quantities must be raised to a uniform power')
---> 88         return f(self, other, *args)
     89     return g
     90

c:\python27\lib\site-packages\quantities\quantity.pyc in __pow__(self, other)
    319     @check_uniform
    320     def __pow__(self, other):
--> 321         return super(Quantity, self).__pow__(other)
    322
    323     @with_doc(np.ndarray.__ipow__)

c:\python27\lib\site-packages\quantities\quantity.pyc in __array_prepare__(self, obj, context)
    234                 """ufunc %r not supported by quantities
    235                 please file a bug report at https://github.com/python-quantities
--> 236                 """ % uf
    237                 )
    238         return res

ValueError: ufunc <ufunc 'positive'> not supported by quantities
                please file a bug report at https://github.com/python-quantities
`

Thank you for your work!
Cheers

**Comment by ryansclement** [comment]
Getting same error when installing [OpenElectrophys-0.3.5](http://pythonhosted.org/OpenElectrophy/index.html) from command line on 64-bit Windows 7 system.  Traceback suggests that the error occurs during with "import neo" step as well.

**Comment by ryansclement** [comment]
UPDATE (solved issue, I think):   I cloned the GitHub repository to get the latest version of Quantities and then installed the package and tried "import neo" again.  This time, no error and appears to be running the neo module correctly.

**Comment by TomDLT** [comment]
For the lazy: 

> pip install --upgrade git+git://github.com/python-quantities/python-quantities.git@master

**Comment by apdavison** [comment]
A new version of quantities has been released - 0.12.0 - in which this error is fixed.

**Comment by pgleeson** [comment]
@apdavison I'm getting similar errors from a [docker image](https://github.com/OpenSourceBrain/neuralensemble-docker/blob/python2/osb/Dockerfile) which is based on [an image currently using an older version of quantities: neuralensemble/simulationx:py2](https://hub.docker.com/r/neuralensemble/simulationx/builds/). 

Rebuilding the neuralensemble docker images on dockerhub should fix the problem.
