### ISSUE TITLE
Add more information units

### ISSUE THREAD

**Issue by osechet** [python-quantities/python-quantities#142]
Is there a reason why the multiples of byte (KB, MB, GB...) are not defined?

**Comment by apdavison** [comment]
I don't know the answer. One challenge is the different decimal and binary definitions of the prefixes (1000 vs 1024, etc). To do this properly, we should define the IEC prefixes kibi, mebi, gibi, etc. (see https://en.wikipedia.org/wiki/Kilobyte)

This seems like a lot of work, but we'd be happy to receive a pull request.

**Comment by osechet** [comment]
I don't really see the problem with the IEC prefixes. kB, MB... are the SI prefixes and follow the same rules as normal SI prefixes (multiples of 10). 
Regarding the IEC prefixes (that already exist in prefixes.py, btw), it's just another list of UnitInformation to add.
Do I miss something?

**Comment by apdavison** [comment]
Implemented by #143
