### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by thisch** [python-quantities/python-quantities#151]
The current release is older than one year. Would it be possible to create a new release soon?

**Comment by thisch** [comment]
@apdavison What do you think about creating a new release?

**Comment by apdavison** [comment]
I think it's a good idea. First I think we should update the CI configuration to check everything works with the most recent versions of Python & NumPy.

I'll try to find time this week.

**Comment by thisch** [comment]
I can take care of the CI config update if you don't mind.

**Comment by apdavison** [comment]
Released 0.12.3 https://pypi.org/project/quantities/0.12.3/
