### ISSUE TITLE
I write a code in pycharm from windows 10 for getting the data of whois

### ISSUE THREAD

**Issue by Shubham-Goyal123** [python-quantities/python-quantities#155]
I write a code in pycharm from windows 10 for getting the data of whois
like# **import pythonwhois**
i am getting error
 File "C:\python37\lib\sre_parse.py", line 1021, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\s'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>

please help me

_Originally posted by @Shubham-Goyal123 in https://github.com/python-quantities/python-quantities/issues/148#issuecomment-496095702_

**Comment by apdavison** [comment]
It is not clear how this is related to `quantities`. Please could you post the full traceback?
