### ISSUE TITLE
Error when installing via pip install in a python 3.2 virtualenv

### ISSUE THREAD

**Issue by hgrecco** [python-quantities/python-quantities#20]
Hi,

I am running into problems when trying to install quantitites in a virtualenv that is configured to use python 3.2.

Basically, after activating the environment I run:

$ pip install quantities

> ..... a lot of lines ....
> 
> RefactoringTool: /home/hernan/Documents/code/envs/lantz/build/quantities/build/py3k/quantities/constants/quantum.py
> 
> Converting to Python3 via 2to3...
> 
> running egg_info
> 
> error: error in 'egg_base' option: 'pip-egg-info' does not exist or is not a directory

If I then move to /build/quantities and run

$ python setup.py install

everything works fine.

It is not critical but it will be nice to have it working.

Thanks for your work.

**Comment by apdavison** [comment]
Given that Python 3.2 has "end-of-life" status (https://docs.python.org/devguide/#status-of-python-branches) and `pip install` works fine with recent versions of Python, I am closing this.
