### ISSUE TITLE
rescale stopped working for rad and deg

### ISSUE THREAD

**Issue by axelande** [python-quantities/python-quantities#215]
Something broke in version 0.14.0 with regards to `rescale`:
In version 0.13.0:
```
heading = pq.Quantity(10, pq.deg)
print(heading.rescale(pq.rad)) -> array(0.17453293) * rad
```

In version 0.14.0:
```
heading = pq.Quantity(10, pq.deg)
heading.rescale(pq.rad) -> array(0) * rad
```
I can't see anything in changed api in the changelog?

**Comment by apdavison** [comment]
Thanks for reporting this. We'll look into it urgently.

As a workaround, I note that explicitly giving `heading` a float dtype avoids the problem, e.g.

```
heading = pq.Quantity(10.0, pq.deg)
print(heading.rescale(pq.rad)) -> array(0.17453293) * rad
```

**Comment by apdavison** [comment]
@bjodah could you look at this?

**Comment by bjodah** [comment]
@apdavison, sure I'll look into this right away, I think I see what's happening here: numpy casting rules aren't really well suited for integer types in `quantities`. I'll try to put a PR together.

**Comment by apdavison** [comment]
Many thanks for the quick response @bjodah !

@axelande I've made a bug-fix release. Updating to 0.14.1 should fix the problem.
