### ISSUE TITLE
Losing dimensions in np.average

### ISSUE THREAD

**Issue by Gianfilippo980** [python-quantities/python-quantities#240]
I am experiencing some inconsistencies in the behavior of numpy's average when called on an array:
I would expect to behave like in this test that I did:
![image](https://github.com/user-attachments/assets/93695c21-2603-4d7f-93e8-81292e1e0ca9)
With the result of a weighted average keeping the original dimensions.
But when I run it in my program:
![image](https://github.com/user-attachments/assets/7111f677-f2cf-4925-9a6b-3342c06d422d)
You can see that I lose the dimensions
![image](https://github.com/user-attachments/assets/9a8a0e13-8f46-4a26-a7ac-055aede1b1c0)

Now, I can just add the ns back to the average, but if I don't understand why it lost them, one day I could end with ns squared and, most importantly, not understanding this module.

**Comment by Gianfilippo980** [comment]
Note that all the snippets are coming from the same Jupiter Notebook.

**Comment by zm711** [comment]
I can't replicate this (but I'm basically doing something similar to your example above: 

![image](https://github.com/user-attachments/assets/2c1cc673-5606-4bb9-a864-fdd8a5d5b0c1)

What is the class? I wonder if adding your class into the weights for this is breaking it. Could you try

```python
weights = np.array(self.Qval[q_filter])
t_0_ev =np.average(t_arr, weights=weights)
print(t_0_ev)
```

**Comment by Gianfilippo980** [comment]
Indeed, mowing the weights to a np.array as you suggested fixes this, self.Qval is a field of an entry of an Awkward Array.
```
import awkward as ak
import quantities as pq
import numpy as np

aw_arr = ak.Array([[[1,2,3],[4,5.3,6]],
                   [[7,8],[9,10]]])

quant_arr = np.array(aw_arr[0,1])*pq.ns
print(np.average(quant_arr, weights= aw_arr[0,1]))
weig_arr = np.array(aw_arr[0,1,:])
print(np.average(quant_arr, weights= weig_arr))

```
Produces:

> 5.234640522875817
5.234640522875817 ns
/tmp/ipykernel_1643/2506223510.py:8: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  quant_arr = np.array(aw_arr[0,1])*pq.ns
/tmp/ipykernel_1643/2506223510.py:10: DeprecationWarning: __array__ implementation doesn't accept a copy keyword, so passing copy=False failed. __array__ must implement 'dtype' and 'copy' keyword arguments.
  weig_arr = np.array(aw_arr[0,1,:])

Yes, this operation raises deprecation warnings, but I can't really avoid Awkward Arrays.

**Comment by zm711** [comment]
@apdavison, I don't know if we support awkward array stuff. 

It seems like my solution could at least work for your purposes. You convert the awkward array to a np.array before using it?

**Comment by Gianfilippo980** [comment]
Sure, I consider my issue fixed now. Thanks for your assistance.
