### ISSUE TITLE
Crashes w/ imshow

### ISSUE THREAD

**Issue by mankoff** [python-quantities/python-quantities#65]
```
foo = np.arange(256).reshape(16,16) *pq.m²
imshow(foo)
```

crashes, and crashes badly enough that if you then run

`imshow(data.magnitude)` it still crashes. A `clf()` fixes the problem. 

`plot(data)` works. Seems like `imshow()` should too.

**Comment by apdavison** [comment]
This seems to have been fixed somewhere along the way. The following works as of v0.16.1:

```
import matplotlib.pyplot as plt
import numpy as np
import quantities as pq

foo = np.arange(256).reshape(16,16) *pq.m**2
plt.imshow(foo)
plt.show()
```
