### ISSUE TITLE
isclose, allclose and less_equal ufunc not supported

### ISSUE THREAD

**Issue by mikofski** [python-quantities/python-quantities#76]
FYI - bummer.

        2188     array([True, False])
        2189     >>> np.isclose([1.0, np.nan], [1.0, np.nan], equal_nan=True)
        2190     array([True, True])
        2191     """
        2192     def within_tol(x, y, atol, rtol):
     -> 2193         with errstate(invalid='ignore'):
        2194             result = less_equal(abs(x-y), atol + rtol * abs(y))
        2195         if isscalar(a) and isscalar(b):
        2196             result = bool(result)
        2197         return result
        2198
    *** ValueError: ufunc %r not supported by quantities
                    please file a bug report at https://github.com/python-quantities

**Comment by bjodah** [comment]
@mikofski did you find a reliable work around for this?
