### ISSUE TITLE
np.fix fails

### ISSUE THREAD

**Issue by ddale** [python-quantities/python-quantities#8]
Test suite failure:

```
======================================================================
FAIL: test_fix (quantities.tests.test_umath.TestUmath)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/darren/Projects/python-quantities/quantities/tests/test_umath.py", line 159, in test_fix
    raise self.failureException(e)
AssertionError: Unable to convert between units of "dimensionless" and "degF"
```

**Comment by yarikoptic** [comment]
test_fix has "failed" to fail for me on Debian sid with python3 and numpy 1:1.16.2-1 ... I guess I will just remove expected failure tag for the package.  It would be nice if those expected failures were annotated on why they are expected to fail.  But fadb0b58bb24fdde1c8cc584aa7e65f1e7c58d17 didn't provide any detail
