### ISSUE TITLE
Conversation to nanometer fails.

### ISSUE THREAD

**Issue by tikeyknax** [python-quantities/python-quantities#91]
I was just thinking about using the python-quantities package, so I did a basic test to see if it works for my purposes. Unfortunately, there seems to be an error when converting to nanometers. For example, when converting from um to nm I get the following (using python-quantities 0.10.1-4.4):

Python 2.7.3 (default, Apr 14 2012, 08:58:41) [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import quantities as pq
>>> q = pq.Quantity(1, 'um')
>>> q.units = pq.nanometer
>>> print q
999 nm

**Comment by ddale** [comment]
Conversion can run into problems with integer data types. Try using a float
instead.
